[tool.poetry]
name = "hello-world-daimon-template"
version = "0.1.0"
description = ""
authors = ["moarshy <marshath@gmail.com>"]
readme = "README.md"
packages = [
    { include = "hello_world_daimon_template", from = "." },
]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
